-- MySQL Script generated by MySQL Workbench
-- qua 22 fev 2023 16:11:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sigedo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sigedo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sigedo` DEFAULT CHARACTER SET utf8mb4 ;
USE `sigedo` ;

-- -----------------------------------------------------
-- Table `sigedo`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedo`.`auth_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(128) NULL DEFAULT NULL,
  `last_name` VARCHAR(128) NULL DEFAULT NULL,
  `email` VARCHAR(512) NULL DEFAULT NULL,
  `password` VARCHAR(512) NULL DEFAULT NULL,
  `registration_key` VARCHAR(512) NULL DEFAULT NULL,
  `reset_password_key` VARCHAR(512) NULL DEFAULT NULL,
  `registration_id` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sigedo`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedo`.`aluno` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `identidade` VARCHAR(512) NULL DEFAULT NULL,
  `matricula` VARCHAR(512) NULL DEFAULT NULL,
  `nome` VARCHAR(512) NULL DEFAULT NULL,
  `civil` VARCHAR(512) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `curso` VARCHAR(512) NULL DEFAULT NULL,
  `periodo` INT(11) NULL DEFAULT NULL,
  `endereco` LONGTEXT NULL DEFAULT NULL,
  `email` VARCHAR(512) NULL DEFAULT NULL,
  `telefone` VARCHAR(512) NULL DEFAULT NULL,
  `is_active` CHAR(1) NULL DEFAULT NULL,
  `created_on` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `modified_on` DATETIME NULL DEFAULT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `created_by__idx` (`created_by` ASC) VISIBLE,
  INDEX `modified_by__idx` (`modified_by` ASC) VISIBLE,
  CONSTRAINT `aluno_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `sigedo`.`auth_user` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `aluno_ibfk_2`
    FOREIGN KEY (`modified_by`)
    REFERENCES `sigedo`.`auth_user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sigedo`.`auth_cas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedo`.`auth_cas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `created_on` DATETIME NULL DEFAULT NULL,
  `service` VARCHAR(512) NULL DEFAULT NULL,
  `ticket` VARCHAR(512) NULL DEFAULT NULL,
  `renew` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id__idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `auth_cas_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sigedo`.`auth_user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sigedo`.`auth_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedo`.`auth_event` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `time_stamp` DATETIME NULL DEFAULT NULL,
  `client_ip` VARCHAR(512) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `origin` VARCHAR(512) NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id__idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `auth_event_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sigedo`.`auth_user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sigedo`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedo`.`auth_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(512) NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sigedo`.`auth_membership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedo`.`auth_membership` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `group_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id__idx` (`user_id` ASC) VISIBLE,
  INDEX `group_id__idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_membership_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sigedo`.`auth_user` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `auth_membership_ibfk_2`
    FOREIGN KEY (`group_id`)
    REFERENCES `sigedo`.`auth_group` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sigedo`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedo`.`auth_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(512) NULL DEFAULT NULL,
  `table_name` VARCHAR(512) NULL DEFAULT NULL,
  `record_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `group_id__idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_permission_ibfk_1`
    FOREIGN KEY (`group_id`)
    REFERENCES `sigedo`.`auth_group` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sigedo`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedo`.`empresa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NULL DEFAULT NULL,
  `razao` VARCHAR(512) NULL DEFAULT NULL,
  `nome` VARCHAR(512) NULL DEFAULT NULL,
  `email` VARCHAR(512) NULL DEFAULT NULL,
  `telefone` VARCHAR(512) NULL DEFAULT NULL,
  `endereco` LONGTEXT NULL DEFAULT NULL,
  `termo` VARCHAR(512) NULL DEFAULT NULL,
  `is_active` CHAR(1) NULL DEFAULT NULL,
  `created_on` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `modified_on` DATETIME NULL DEFAULT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `created_by__idx` (`created_by` ASC) VISIBLE,
  INDEX `modified_by__idx` (`modified_by` ASC) VISIBLE,
  CONSTRAINT `empresa_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `sigedo`.`auth_user` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `empresa_ibfk_2`
    FOREIGN KEY (`modified_by`)
    REFERENCES `sigedo`.`auth_user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sigedo`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedo`.`professor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `nome` VARCHAR(512) NULL DEFAULT NULL,
  `email` VARCHAR(512) NULL DEFAULT NULL,
  `telefone` VARCHAR(512) NULL DEFAULT NULL,
  `is_active` CHAR(1) NULL DEFAULT NULL,
  `created_on` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `modified_on` DATETIME NULL DEFAULT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `created_by__idx` (`created_by` ASC) VISIBLE,
  INDEX `modified_by__idx` (`modified_by` ASC) VISIBLE,
  CONSTRAINT `professor_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `sigedo`.`auth_user` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `professor_ibfk_2`
    FOREIGN KEY (`modified_by`)
    REFERENCES `sigedo`.`auth_user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sigedo`.`estagio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigedo`.`estagio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `aluno` INT(11) NULL DEFAULT NULL,
  `empresa` INT(11) NULL DEFAULT NULL,
  `professor` INT(11) NULL DEFAULT NULL,
  `supervisor` VARCHAR(512) NULL DEFAULT NULL,
  `data_inicio` DATE NULL DEFAULT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  `observacao` LONGTEXT NULL DEFAULT NULL,
  `situacao` VARCHAR(512) NULL DEFAULT NULL,
  `is_active` CHAR(1) NULL DEFAULT NULL,
  `created_on` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `modified_on` DATETIME NULL DEFAULT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `aluno__idx` (`aluno` ASC) VISIBLE,
  INDEX `empresa__idx` (`empresa` ASC) VISIBLE,
  INDEX `professor__idx` (`professor` ASC) VISIBLE,
  INDEX `created_by__idx` (`created_by` ASC) VISIBLE,
  INDEX `modified_by__idx` (`modified_by` ASC) VISIBLE,
  CONSTRAINT `estagio_ibfk_1`
    FOREIGN KEY (`aluno`)
    REFERENCES `sigedo`.`aluno` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `estagio_ibfk_2`
    FOREIGN KEY (`empresa`)
    REFERENCES `sigedo`.`empresa` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `estagio_ibfk_3`
    FOREIGN KEY (`professor`)
    REFERENCES `sigedo`.`professor` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `estagio_ibfk_4`
    FOREIGN KEY (`created_by`)
    REFERENCES `sigedo`.`auth_user` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `estagio_ibfk_5`
    FOREIGN KEY (`modified_by`)
    REFERENCES `sigedo`.`auth_user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
